/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Dados.Veiculo;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import util.Controle_Excel_Veiculo;
import util.Controle_TXT_Veiculo;

/**
 *
 * @author Alunos
 */
public class AdicionarVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarVeiculo
     */
    public AdicionarVeiculo() {
        initComponents();
        
        //Crio as Datas Limites para limitar o Spinner
        Date DataMin = new GregorianCalendar(1886, Calendar.JANUARY,  29).getTime();
        //Recebe a Data Atual
        Date Inicial = new Date();
        
        //Coloca o Spinner Recebendo o Valor Inicial
        //Limita ele com o Valor Minimo
        //Limita ele com o Valor Maximo sendo o Inicial
        //e Faz ele pular Ano em Ano
        SpnrAno.setModel(new SpinnerDateModel(Inicial, DataMin, Inicial, Calendar.YEAR));
        
        //Faz Aparecer Apenas os Anos
        SpnrAno.setEditor(new JSpinner.DateEditor(SpnrAno, "yyyy"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxFPlaca = new javax.swing.JTextField();
        TxFMarca = new javax.swing.JTextField();
        TxFModelo = new javax.swing.JTextField();
        RdBntAtivo = new javax.swing.JRadioButton();
        RdBntInativo = new javax.swing.JRadioButton();
        SpnrAno = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        BntLimpar = new javax.swing.JButton();
        BntMenu = new javax.swing.JButton();
        bntAdd = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemCtrlVeic = new javax.swing.JMenuItem();
        MenuItemCtrlMov = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemAddMovi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabel1.setText("Adicionar Veículo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Marca");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Placa");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Modelo");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Ano De Fabricação");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Estado");

        TxFPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxFPlacaActionPerformed(evt);
            }
        });

        buttonGroup1.add(RdBntAtivo);
        RdBntAtivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RdBntAtivo.setText("Ativo");

        buttonGroup1.add(RdBntInativo);
        RdBntInativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RdBntInativo.setText("Inativo");

        SpnrAno.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(TxFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RdBntInativo)
                            .addComponent(RdBntAtivo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpnrAno, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SpnrAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RdBntAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RdBntInativo)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        BntLimpar.setText("Limpar");
        BntLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntLimparActionPerformed(evt);
            }
        });

        BntMenu.setText("Menu");
        BntMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntMenuActionPerformed(evt);
            }
        });

        bntAdd.setText("Adicionar");
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(BntLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Controles");

        MenuItemCtrlVeic.setText("Veículo");
        MenuItemCtrlVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCtrlVeicActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCtrlVeic);

        MenuItemCtrlMov.setText("Movimentação");
        MenuItemCtrlMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCtrlMovActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCtrlMov);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Adicionar");

        MenuItemAddMovi.setText("Movimentação");
        MenuItemAddMovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddMoviActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemAddMovi);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxFPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxFPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxFPlacaActionPerformed

    private void BntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntLimparActionPerformed
        //Limpa os Text Fields
        this.Limpar();
    }//GEN-LAST:event_BntLimparActionPerformed

    private void BntMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntMenuActionPerformed
        //Abre uma nova tela e fecha a atual
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntMenuActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed

        
        //Verifica se Algum dos Campos Não está escrito
        if(TxFPlaca.getText().equals("") || TxFMarca.getText().equals("") || TxFModelo.getText().equals("") || buttonGroup1.getSelection() == null){
            JOptionPane.showMessageDialog(null, "Informe as informações em todos os campos!");
        }else{
            
            //Serve para montar o Caminho do Arquivo usando onde o programa está sendo rodado
            String Caminho = System.getProperty("user.dir") + "\\Veiculo.xlsx";
            ArrayList<Veiculo> Lista = Controle_Excel_Veiculo.LerExcel(Caminho);
            
            for(Veiculo veiculo : Lista){
                if(TxFPlaca.getText().equalsIgnoreCase(veiculo.getPlaca())){
                    JOptionPane.showMessageDialog(null, "Placa ja Existente, Tente Outra!");
                    return;
                }
            }
            
            
            //Recebe o Valor do Spinner
            Date Data = (Date) SpnrAno.getValue();
        
            //Classe para arrumar a Data Recebida
            Calendar c = Calendar.getInstance();
            //Recebe o Valor que estava no Spinner
            c.setTime(Data);
            //e Coloca em uma variavel apenas o Ano
            int Ano = c.get(Calendar.YEAR);
        
            boolean Botao = false;
        
            //Verifica qual dos botões esta ativo
            if(RdBntAtivo.isSelected()){
                Botao = true;
            }else if(RdBntInativo.isSelected()){
                Botao = false;
            }
        
            //Le o Arquivo antes de Adicionar para funcionar a automatização do ID
            Controle_TXT_Veiculo.LerArquivo();
        
            Veiculo veiculo = new Veiculo(0,TxFPlaca.getText(),
                                        TxFMarca.getText(),TxFModelo.getText(),
                                        Ano,Botao);
        
            Controle_TXT_Veiculo.SalvarLinha(veiculo);
            Lista = Controle_TXT_Veiculo.LerArquivo();
            Controle_Excel_Veiculo.Transf_Excel(Lista, Caminho);
        
            this.Limpar();
            }
    }//GEN-LAST:event_bntAddActionPerformed

    private void MenuItemCtrlMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCtrlMovActionPerformed
        //Abre uma nova tela e fecha a atual
        new ControleMovimentacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemCtrlMovActionPerformed

    private void MenuItemCtrlVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCtrlVeicActionPerformed
        //Abre uma nova tela e fecha a atual
        new ControleVeiculo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemCtrlVeicActionPerformed

    private void MenuItemAddMoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddMoviActionPerformed
        //Abre uma nova tela e fecha a atual
        new AdicionarMovimentacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemAddMoviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarVeiculo().setVisible(true);
            }
        });
    }
    
    //Metodo de Limpar os Campos
    public void Limpar(){
        Date Inicial = new Date();
        SpnrAno.setValue(Inicial);
        TxFPlaca.setText("");
        TxFMarca.setText("");
        TxFModelo.setText("");
        buttonGroup1.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntLimpar;
    private javax.swing.JButton BntMenu;
    private javax.swing.JMenuItem MenuItemAddMovi;
    private javax.swing.JMenuItem MenuItemCtrlMov;
    private javax.swing.JMenuItem MenuItemCtrlVeic;
    private javax.swing.JRadioButton RdBntAtivo;
    private javax.swing.JRadioButton RdBntInativo;
    private javax.swing.JSpinner SpnrAno;
    private javax.swing.JTextField TxFMarca;
    private javax.swing.JTextField TxFModelo;
    private javax.swing.JTextField TxFPlaca;
    private javax.swing.JButton bntAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}