/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Dados.Movimentacao;
import Dados.TipoDespesa;
import Dados.Veiculo;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.text.NumberFormatter;
import util.Controle_Excel_Despesa;
import util.Controle_Excel_Movimentacao;
import util.Controle_Excel_Veiculo;
import util.Controle_TXT_Despesa;
import util.Controle_TXT_Movimentacao;

/**
 *
 * @author Alunos
 */
public class AdicionarMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form TabelaMovimentacao
     */
    public AdicionarMovimentacao() {
        initComponents();
        
        //Classe Para Modificar o Formatted Field
        //Colocando no Formato que preferir
        ((NumberFormatter) TxFValor.getFormatter()).setFormat(
            new DecimalFormat("#0.00", new DecimalFormatSymbols(Locale.US))
        );
        
        //Crio as Datas Limites para limitar o Spinner
        Date DataMin = new GregorianCalendar(1886, Calendar.JANUARY,  29).getTime();
        //Recebe a Data Atual
        Date Inicial = new Date();
        
        //Coloca o Spinner Recebendo o Valor Inicial
        //Limita ele com o Valor Minimo
        //Limita ele com o Valor Maximo sendo o Inicial
        //e Faz ele pular por Dia
        SpnrData.setModel(new SpinnerDateModel(Inicial, DataMin, Inicial, Calendar.DAY_OF_MONTH));
        
        //Faz Aparecer o Dia/Mes/Ano
        SpnrData.setEditor(new JSpinner.DateEditor(SpnrData, "dd/MM/yyyy"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CmbBxCategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TxFPlaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxADesc = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        SpnrData = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        TxFValor = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        BntLimpar = new javax.swing.JButton();
        BntMenu = new javax.swing.JButton();
        bntAdd = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemCtrlVeic = new javax.swing.JMenuItem();
        MenuItemCtrlMov = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemAddVeic = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabel1.setText("Adicionar Movimentação");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Placa:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        CmbBxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combustível", "Pedágio", "Estacionamento", "Manutenção", "IPVA", "Multas", "Seguro", "Guincho" }));
        CmbBxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbBxCategoriaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("Categorias:");

        TxADesc.setColumns(20);
        TxADesc.setRows(5);
        jScrollPane1.setViewportView(TxADesc);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setText("Valor:");

        SpnrData.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1764730500000L), new java.util.Date(-2648408340000L), new java.util.Date(), java.util.Calendar.DAY_OF_WEEK));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setText("Data:");

        TxFValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SpnrData)
                            .addComponent(TxFPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(TxFValor)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbBxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CmbBxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpnrData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BntLimpar.setText("Limpar");
        BntLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntLimparActionPerformed(evt);
            }
        });

        BntMenu.setText("Menu");
        BntMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntMenuActionPerformed(evt);
            }
        });

        bntAdd.setText("Adicionar");
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(bntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BntLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jMenu1.setText("Controles");

        MenuItemCtrlVeic.setText("Veículo");
        MenuItemCtrlVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCtrlVeicActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCtrlVeic);

        MenuItemCtrlMov.setText("Movimentação");
        MenuItemCtrlMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCtrlMovActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCtrlMov);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Adicionar");

        MenuItemAddVeic.setText("Veículo");
        MenuItemAddVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddVeicActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemAddVeic);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CmbBxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbBxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbBxCategoriaActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
        
        //Verifica se Algum dos Campos Não está escrito
        if(TxFPlaca.getText().equals("") || TxFValor.getText().equals("") || TxADesc.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe as informações em todos os campos!");
        }else{
        
            //Recebe o Valor do Spinner
            Date Data = (Date) SpnrData.getValue();
            
            //Classe para arrumar a Data Recebida
            Calendar c = Calendar.getInstance();
            //Recebe o Valor que estava no Spinner
            c.setTime(Data);
            //e Coloca em Variaveis
            int Dia = c.get(Calendar.DAY_OF_MONTH);
            
            //Por culpa do java Começar tudo em 0 tem que adicionar +1 na hora de Receber
            int Mes = c.get(Calendar.MONTH) + 1;
            int Ano = c.get(Calendar.YEAR);
            
            //Serve para montar o Caminho do Arquivo usando onde o programa está sendo rodado
            String CaminhoVeic = System.getProperty("user.dir") + "\\Veiculo.xlsx";
            String CaminhoMov = System.getProperty("user.dir") + "\\Movimentacao.xlsx";
            String CaminhoD = System.getProperty("user.dir") + "\\Despesa.xlsx";
            
            //Cria as Listas
            ArrayList<Veiculo> listaVeic = Controle_Excel_Veiculo.LerExcel(CaminhoVeic);
            ArrayList<Movimentacao> ListaMov = new ArrayList<>();
            ArrayList<TipoDespesa> ListaD = new ArrayList<>();
            
            //Percorre a Lista Procura o ID do Veiculo pela Placa
            String placaMov = TxFPlaca.getText();
            int idEncontrado = 0;
            for (Veiculo veiculo : listaVeic) {
                if (veiculo.getPlaca().equalsIgnoreCase(placaMov)) {
                    idEncontrado = veiculo.getIDVeiculo();
                break;
                }
            }
            
            //Caso não tenha Encontrado sera avisado
            if (idEncontrado == 0) {
                JOptionPane.showMessageDialog(null, "Placa não encontrada!");
            return;
            }
            
            //Recebe o Valor que está selecionado no Combo Box
            String Categoria = (String) CmbBxCategoria.getSelectedItem();
            
             //Le o Arquivo antes de Adicionar para funcionar a automatização do ID
            Controle_TXT_Movimentacao.LerArquivo();
            
            Movimentacao mov = new Movimentacao(0,idEncontrado,0,TxFPlaca.getText(),Categoria,
                                                TxADesc.getText(),Dia,Mes,Ano,Double.valueOf(TxFValor.getText()));
    
            
            
            Controle_TXT_Movimentacao.SalvarLinha(mov);
            ListaMov = Controle_TXT_Movimentacao.LerArquivo();
            Controle_Excel_Movimentacao.Transf_Excel(ListaMov, CaminhoMov);
            
             //Le o Arquivo antes de Adicionar para funcionar a automatização do ID
            Controle_TXT_Despesa.LerArquivo();
            
            TipoDespesa Despesa = new TipoDespesa(mov.getIDTipoDespesa(),mov.getPlaca(),mov.getCategoria(),mov.getDescricao());
            
            Controle_TXT_Despesa.SalvarLinha(Despesa);
            ListaD = Controle_TXT_Despesa.LerArquivo();
            Controle_Excel_Despesa.Transf_Excel(ListaD, CaminhoD);
        
            this.Limpar();
        }
    }//GEN-LAST:event_bntAddActionPerformed

    private void BntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntLimparActionPerformed
        //Limpa os Text Fields
        this.Limpar();
    }//GEN-LAST:event_BntLimparActionPerformed

    private void BntMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntMenuActionPerformed
        //Abre uma nova tela e fecha a atual
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntMenuActionPerformed

    private void MenuItemCtrlMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCtrlMovActionPerformed
        //Abre uma nova tela e fecha a atual
        new ControleMovimentacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemCtrlMovActionPerformed

    private void MenuItemCtrlVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCtrlVeicActionPerformed
        //Abre uma nova tela e fecha a atual
        new ControleVeiculo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemCtrlVeicActionPerformed

    private void MenuItemAddVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddVeicActionPerformed
        //Abre uma nova tela e fecha a atual
        new AdicionarVeiculo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemAddVeicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarMovimentacao().setVisible(true);
            }
        });
    }
    
    //Metodo de Limpar os Campos
    public void Limpar(){
        Date Inicial = new Date();
        TxFPlaca.setText("");
        SpnrData.setValue(Inicial);
        TxADesc.setText("");
        TxFValor.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntLimpar;
    private javax.swing.JButton BntMenu;
    private javax.swing.JComboBox<String> CmbBxCategoria;
    private javax.swing.JMenuItem MenuItemAddVeic;
    private javax.swing.JMenuItem MenuItemCtrlMov;
    private javax.swing.JMenuItem MenuItemCtrlVeic;
    private javax.swing.JSpinner SpnrData;
    private javax.swing.JTextArea TxADesc;
    private javax.swing.JTextField TxFPlaca;
    private javax.swing.JFormattedTextField TxFValor;
    private javax.swing.JButton bntAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
