/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Dados.Movimentacao;
import Dados.TipoDespesa;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import util.Controle_Excel_Despesa;
import util.Controle_Excel_Movimentacao;
import util.Controle_TXT_Despesa;
import util.Controle_TXT_Movimentacao;

/**
 *
 * @author Alunos
 */
public class ControleMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarMovimentacao
     */
    public ControleMovimentacao() {
        initComponents();
        
        //Serve para montar o Caminho do Arquivo usando onde o programa está sendo rodado
        String Caminho = System.getProperty("user.dir") + "\\Movimentacao.xlsx";
        String CaminhoD = System.getProperty("user.dir") + "\\Despesas.xlsx";
        
        //Quando Inicia a Tela Atualiza o Txt da Movimentacao e Despesa
        ArrayList<Movimentacao> ListaMov = Controle_Excel_Movimentacao.LerExcel(Caminho);
        Controle_TXT_Movimentacao.AtualizarTxtExcel(ListaMov);
        
        ArrayList<TipoDespesa> ListaD = Controle_Excel_Despesa.LerExcel(CaminhoD);
        Controle_TXT_Despesa.AtualizarTxtExcel(ListaD);
        
        //Quando a tela é aberta ja Preenche a tabela
        PreencherTabela("Movimentacao.xlsx");
    }
    
    public void PreencherTabela(String Caminho) {
        //Cria uma Lista com as informações do Excel
        ArrayList<Movimentacao> Lista = Controle_Excel_Movimentacao.LerExcel(Caminho);
        
        //Classe para Modificar a tabela sem modificar diretamente na interface
        DefaultTableModel modelo = (DefaultTableModel) TableMov.getModel();
        
        //Seta o Numero de linhas da coluna para evitar algum erro
        modelo.setNumRows(0);
        
        //Percorre a Lista e colocando informações na Tabela
        for(Movimentacao movimentacao : Lista){
            modelo.addRow(new Object[]{
                movimentacao.getIDMovimentacao(),
                movimentacao.getIDVeiculo(),
                movimentacao.getIDTipoDespesa(),
                movimentacao.getPlaca(),
                movimentacao.getCategoria(),
                movimentacao.getDescricao(),
                movimentacao.getDia(),
                movimentacao.getMes(),
                movimentacao.getAno(),
                movimentacao.getValor()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableVeiculo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableMov = new javax.swing.JTable();
        BntAdd = new javax.swing.JButton();
        BntMenu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuControle = new javax.swing.JMenu();
        MenuItemCtrlVeiculo = new javax.swing.JMenuItem();
        MenuAdd = new javax.swing.JMenu();
        MenuItemAddVeiculo = new javax.swing.JMenuItem();
        MenuItemAddMov = new javax.swing.JMenuItem();

        TableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Veículo", "Placa", "Marca", "Modelo", "Ano De Fabricação", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableVeiculo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 40)); // NOI18N
        jLabel2.setText("Controle De Movimentaçao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel2)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(38, 38, 38))
        );

        TableMov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Movimentação", "ID Veículo", "ID Despesa", "Placa", "Categoria", "Descrição", "Dia", "Mes", "Ano", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableMov);

        BntAdd.setText("Adicionar");
        BntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAddActionPerformed(evt);
            }
        });

        BntMenu.setText("Menu");
        BntMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        MenuControle.setText("Controles");

        MenuItemCtrlVeiculo.setText("Veículo");
        MenuItemCtrlVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCtrlVeiculoActionPerformed(evt);
            }
        });
        MenuControle.add(MenuItemCtrlVeiculo);

        jMenuBar1.add(MenuControle);

        MenuAdd.setText("Adicionar");

        MenuItemAddVeiculo.setText("Veículo");
        MenuItemAddVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddVeiculoActionPerformed(evt);
            }
        });
        MenuAdd.add(MenuItemAddVeiculo);

        MenuItemAddMov.setText("Movimentação");
        MenuItemAddMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddMovActionPerformed(evt);
            }
        });
        MenuAdd.add(MenuItemAddMov);

        jMenuBar1.add(MenuAdd);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAddActionPerformed
        //Abre uma nova tela e fecha a atual
        new AdicionarMovimentacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntAddActionPerformed

    private void BntMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntMenuActionPerformed
        //Abre uma nova tela e fecha a atual
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntMenuActionPerformed

    private void MenuItemCtrlVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCtrlVeiculoActionPerformed
        //Abre uma nova tela e fecha a atual
        new ControleVeiculo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemCtrlVeiculoActionPerformed

    private void MenuItemAddVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddVeiculoActionPerformed
        //Abre uma nova tela e fecha a atual
        new AdicionarVeiculo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemAddVeiculoActionPerformed

    private void MenuItemAddMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddMovActionPerformed
        //Abre uma nova tela e fecha a atual
        new AdicionarMovimentacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemAddMovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntAdd;
    private javax.swing.JButton BntMenu;
    private javax.swing.JMenu MenuAdd;
    private javax.swing.JMenu MenuControle;
    private javax.swing.JMenuItem MenuItemAddMov;
    private javax.swing.JMenuItem MenuItemAddVeiculo;
    private javax.swing.JMenuItem MenuItemCtrlVeiculo;
    private javax.swing.JTable TableMov;
    private javax.swing.JTable TableVeiculo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
