/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Dados.Veiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Controle_Excel_Veiculo;
import util.Controle_TXT_Veiculo;

/**
 *
 * @author Alunos
 */
public class ControleVeiculo extends javax.swing.JFrame {

    public ControleVeiculo() {
        initComponents();
        
        //Serve para montar o Caminho do Arquivo usando onde o programa está sendo rodado
        String Caminho = System.getProperty("user.dir") + "\\Veiculo.xlsx";
        
        //Quando Inicia a Tela Atualiza o Txt
        ArrayList<Veiculo> Lista = Controle_Excel_Veiculo.LerExcel(Caminho);
        Controle_TXT_Veiculo.AtualizarTxtExcel(Lista);
        
        //Quando a tela é aberta ja Preenche a tabela
        PreencherTabela("Veiculo.xlsx");
    }
    
    public void PreencherTabela(String Caminho) {
        //Cria uma Lista com as informações do Excel
        ArrayList<Veiculo> Lista = Controle_Excel_Veiculo.LerExcel(Caminho);
        
        //Classe para Modificar a tabela sem modificar diretamente na interface
        DefaultTableModel modelo = (DefaultTableModel) TableVeiculo.getModel();
        
        //Seta o Numero de linhas da coluna para evitar algum erro
        modelo.setNumRows(0);
        
        //Percorre a Lista e colocando informações na Tabela
        for (Veiculo veiculo : Lista) {
            modelo.addRow(new Object[]{
                veiculo.getIDVeiculo(),
                veiculo.getPlaca(),
                veiculo.getMarca(),
                veiculo.getModelo(),
                veiculo.getAnoFab(),
                veiculo.getEstadoDoVeiculoTexto()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableVeiculo = new javax.swing.JTable();
        BntAdd = new javax.swing.JButton();
        BntAttTxt = new javax.swing.JButton();
        BntEstado = new javax.swing.JButton();
        BntMenu1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuControle = new javax.swing.JMenu();
        MenuItemCtrlMov = new javax.swing.JMenuItem();
        MenuAdd = new javax.swing.JMenu();
        MenuItemAddVeiculo = new javax.swing.JMenuItem();
        MenuItemAddMov = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 46)); // NOI18N
        jLabel1.setText("Controle De Veículos");

        TableVeiculo.setAutoCreateRowSorter(true);
        TableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Veículo", "Placa", "Marca", "Modelo", "Ano De Fabricação", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableVeiculo);

        BntAdd.setText("Adicionar");
        BntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAddActionPerformed(evt);
            }
        });

        BntAttTxt.setText("Atualizar Txt");
        BntAttTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAttTxtActionPerformed(evt);
            }
        });

        BntEstado.setText("Mudar Estado");
        BntEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntEstadoActionPerformed(evt);
            }
        });

        BntMenu1.setText("Menu");
        BntMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntAttTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(BntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(BntEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(BntAttTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(BntMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuControle.setText("Controles");

        MenuItemCtrlMov.setText("Movimentações");
        MenuItemCtrlMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCtrlMovActionPerformed(evt);
            }
        });
        MenuControle.add(MenuItemCtrlMov);

        jMenuBar1.add(MenuControle);

        MenuAdd.setText("Adicionar");

        MenuItemAddVeiculo.setText("Veículo");
        MenuItemAddVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddVeiculoActionPerformed(evt);
            }
        });
        MenuAdd.add(MenuItemAddVeiculo);

        MenuItemAddMov.setText("Movimentação");
        MenuItemAddMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddMovActionPerformed(evt);
            }
        });
        MenuAdd.add(MenuItemAddMov);

        jMenuBar1.add(MenuAdd);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemCtrlMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCtrlMovActionPerformed
        //Abre uma nova tela e fecha a atual
        new ControleMovimentacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemCtrlMovActionPerformed

    private void BntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAddActionPerformed
        //Abre uma nova tela e fecha a atual
        new AdicionarVeiculo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntAddActionPerformed

    private void MenuItemAddVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddVeiculoActionPerformed
        //Abre uma nova tela e fecha a atual 
        new AdicionarVeiculo().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_MenuItemAddVeiculoActionPerformed

    private void BntAttTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAttTxtActionPerformed
        //Atualiza o Txt com as novas Informações
        String Caminho = "Veiculo.xlsx";
        ArrayList<Veiculo> Lista = Controle_Excel_Veiculo.LerExcel(Caminho);
        
        Controle_TXT_Veiculo.AtualizarTxtExcel(Lista);
    }//GEN-LAST:event_BntAttTxtActionPerformed

    private void MenuItemAddMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddMovActionPerformed
        //Abre uma nova tela e fecha a atual
        new AdicionarMovimentacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemAddMovActionPerformed

    private void BntEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntEstadoActionPerformed
        //Muda o Estado do veiculo
        String Caminho = "Veiculo.xlsx";
        
        ArrayList<Veiculo> Lista = Controle_Excel_Veiculo.LerExcel(Caminho);
        //Recebe a Linha selecionada
        int linha = TableVeiculo.getSelectedRow();
        
        //Caso nenhuma linha esteja selecionada recebe o valor de -1
        if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um veículo!");
        return;
        }
        
        //Muda as Informações do Excel do veiculo que está selecionado
        Veiculo veiculo = Lista.get(linha);
        
        //novoEstado Recebe o Valor contrario do Valor Atual do isEstadoDoVeic
        //Caso seja "true" ele irá receber "false"
        //e ja seta o novoEstado
        boolean novoEstado = !veiculo.isEstadoDoVeic();
        veiculo.setEstadoDoVeic(novoEstado);
        
        //Classe para Modificar a tabela sem modificar diretamente na interface
        DefaultTableModel modelo = (DefaultTableModel) TableVeiculo.getModel();
        
        //Muda o valor da Linha selecionada e da Coluna 5 Colocando o Estado em Texto
        modelo.setValueAt(veiculo.getEstadoDoVeiculoTexto(), linha, 5);
        
        //e para Finalizar Atualiza o Arquivo
        Controle_Excel_Veiculo.Transf_Excel(Lista, Caminho);
        Controle_TXT_Veiculo.AtualizarTxtExcel(Lista);
        
        JOptionPane.showMessageDialog(null, "Estado alterado para: " + veiculo.getEstadoDoVeiculoTexto());
    }//GEN-LAST:event_BntEstadoActionPerformed

    private void BntMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntMenu1ActionPerformed
        
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntAdd;
    private javax.swing.JButton BntAttTxt;
    private javax.swing.JButton BntEstado;
    private javax.swing.JButton BntMenu1;
    private javax.swing.JMenu MenuAdd;
    private javax.swing.JMenu MenuControle;
    private javax.swing.JMenuItem MenuItemAddMov;
    private javax.swing.JMenuItem MenuItemAddVeiculo;
    private javax.swing.JMenuItem MenuItemCtrlMov;
    private javax.swing.JTable TableVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}


