/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;
import util.Controle_Excel_Movimentacao;

/**
 *
 * @author gusta
 */
public class Relatorios extends javax.swing.JFrame {

    /**
     * Creates new form Relatorios
     */
    public Relatorios() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BntSomaGMes = new javax.swing.JButton();
        BntSomaIPVAAno = new javax.swing.JButton();
        BntDeterVeic = new javax.swing.JButton();
        BntGastosCombMes = new javax.swing.JButton();
        BntRelatorioMulta = new javax.swing.JButton();
        BntVeicInativo = new javax.swing.JButton();
        BntMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabel1.setText("Relatórios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        BntSomaGMes.setText("Somatório Geral do Mês");
        BntSomaGMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntSomaGMesActionPerformed(evt);
            }
        });

        BntSomaIPVAAno.setText("Somatório de IPVA do Ano");
        BntSomaIPVAAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntSomaIPVAAnoActionPerformed(evt);
            }
        });

        BntDeterVeic.setText("Determinado Veículo");
        BntDeterVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntDeterVeicActionPerformed(evt);
            }
        });

        BntGastosCombMes.setText("Gastos De combustível no Mês");
        BntGastosCombMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntGastosCombMesActionPerformed(evt);
            }
        });

        BntRelatorioMulta.setText("Relatório das Multas");
        BntRelatorioMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntRelatorioMultaActionPerformed(evt);
            }
        });

        BntVeicInativo.setText("Veículos Inativos ou Ativos");
        BntVeicInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntVeicInativoActionPerformed(evt);
            }
        });

        BntMenu.setText("Menu");
        BntMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BntDeterVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BntSomaGMes, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BntGastosCombMes, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(BntVeicInativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(152, 152, 152)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BntSomaIPVAAno, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(BntRelatorioMulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(61, 61, 61))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntSomaGMes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntDeterVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntSomaIPVAAno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntGastosCombMes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntRelatorioMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntVeicInativo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BntSomaGMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntSomaGMesActionPerformed
        
        //Serve para montar o Caminho do Arquivo usando onde o programa está sendo rodado
        String Caminho = System.getProperty("user.dir") + "\\Movimentacao.xlsx";
        
        //Faz o Calculo da Soma Do Mes
        Controle_Excel_Movimentacao.ValorTotalMes = 0;
        Controle_Excel_Movimentacao.MesValor = Integer.parseInt(JOptionPane.showInputDialog("Mes: "));
        Controle_Excel_Movimentacao.LerExcel(Caminho);
        
        double TotalMes = Controle_Excel_Movimentacao.ValorTotalMes;
        JOptionPane.showMessageDialog(null, "Total Mes: "+TotalMes);
    }//GEN-LAST:event_BntSomaGMesActionPerformed

    private void BntSomaIPVAAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntSomaIPVAAnoActionPerformed
        
        //Serve para montar o Caminho do Arquivo usando onde o programa está sendo rodado
        String Caminho = System.getProperty("user.dir") + "\\Movimentacao.xlsx";
        
        //Faz o Calculo do IPVA do Ano
        Controle_Excel_Movimentacao.AnoIPVA = Integer.parseInt(JOptionPane.showInputDialog("Ano: "));
        Controle_Excel_Movimentacao.ValorIPVAAno = 0;
        Controle_Excel_Movimentacao.LerExcel(Caminho);
        
        double TotalIPVAAno = Controle_Excel_Movimentacao.ValorIPVAAno;
        JOptionPane.showMessageDialog(null, "Total Gasto em IPVA no Ano: "+TotalIPVAAno);
    }//GEN-LAST:event_BntSomaIPVAAnoActionPerformed
    
    public static String VeicDeter;
    
    private void BntDeterVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntDeterVeicActionPerformed
        
        //Recebe a Placa do Veiculo Desejado
        //Abre uma nova tela e fecha a atual
        VeicDeter = JOptionPane.showInputDialog("Digite a Placa do Veículo: ");
        new RelatorioDeterVeic().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntDeterVeicActionPerformed

    private void BntGastosCombMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntGastosCombMesActionPerformed
        
        //Serve para montar o Caminho do Arquivo usando onde o programa está sendo rodado
        String Caminho = System.getProperty("user.dir") + "\\Movimentacao.xlsx";
        
        //Faz o Calculo Dos Gastos Com Combustivel
        Controle_Excel_Movimentacao.MesValorComb = Integer.parseInt(JOptionPane.showInputDialog("Mes: "));
        Controle_Excel_Movimentacao.ValorTotalMesComb = 0;
        Controle_Excel_Movimentacao.LerExcel(Caminho);
        
        double ValorTotal = Controle_Excel_Movimentacao.ValorTotalMesComb;
        JOptionPane.showMessageDialog(null, "Total De Gastos em Combustível no mês: "+ValorTotal);
    }//GEN-LAST:event_BntGastosCombMesActionPerformed
    
    public static String PlacaMulta;
    public static int AnoMulta;
    
    private void BntRelatorioMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntRelatorioMultaActionPerformed
        
        //Recebe a Placa e o Ano Desejado
        //Abre uma nova tela e fecha a atual
        PlacaMulta = JOptionPane.showInputDialog("Digite a Placa do Veículo: ");
        AnoMulta = Integer.parseInt(JOptionPane.showInputDialog("Digite o Ano Da Multa"));
        new RelatorioMultas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntRelatorioMultaActionPerformed

    private void BntVeicInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntVeicInativoActionPerformed
        //Abre uma nova tela e fecha a atual
        new RelatorioVeicInativo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntVeicInativoActionPerformed

    private void BntMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntMenuActionPerformed
        //Abre uma nova tela e fecha a atual
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BntMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntDeterVeic;
    private javax.swing.JButton BntGastosCombMes;
    private javax.swing.JButton BntMenu;
    private javax.swing.JButton BntRelatorioMulta;
    private javax.swing.JButton BntSomaGMes;
    private javax.swing.JButton BntSomaIPVAAno;
    private javax.swing.JButton BntVeicInativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
